### ISSUE TITLE
Various bugs/oversights

### ISSUE THREAD

**Issue by totalgooberdeath** [quentin452/TragicMC2-Continuation#4]
I'm a huge soyboy for TragicMC2. I don't know if I should be posting here, but here's a few bugs I've noticed in the original and in this version

## 1. Ender Amulet crash (Major crash)
Ender Amulet lets you mine blocks faster with your bare hands and silktouches them if you do it this way. If you mine any part of a double-tall plant block (e.g, grass, rose bush, large fern, etc.), the world will be corrupted and you will *have to* load from a backup.
**HOW TO RECREATE**
1. Spawn in/obtain Ender Amulet
2. Equip ender amulet (either right click with an empty amulet slot available or navigate to the amulet GUI and equip it manually)
3. Punch any double-tall plant block
4. Game will turn into a greyish-blue screen and boot you out of the world. The world will crash every time it tries to be reloaded

**TEMPORARY FIX**
There exists a temporary fix in the form of simply disabling the amulet's effect in the config, leaving it with no ability whatsoever. 

## 3. Chest item stacksizes of 0 (Bug)
 [In the 1.7.10 version of TragicMC2, chest loot added by the mod can have a minimum stacksize of 0](https://github.com/TragicNeko/TragicMC2/blob/b2be94311c192ab9561438497eb957fbe42dddd0/src/main/java/tragicneko/tragicmc/TragicItems.java#L285), meaning that items will appear in chests but won't actually exist on the server side.

**HOW TO RECREATE**
1. Spawn in a structure (or encounter it naturally)
2. Open up the chest
3. Shift click random items into an empty inventory. If the item has a stacksize of 0, it will not go into your inventory.
4. Break chest to force it to drop any items. Notice how the items with 0 stacksize do not drop because they do not actually exist.

[In the 1.8 version of TragicMC2, this bug has been fixed](https://github.com/TragicNeko/TragicMC2-1.8/blob/947c692193919465a63b97080633b9f858fb39e5/src/main/java/tragicneko/tragicmc/util/ChestHooks.java#L18).

## 4. Aeris can break bedrock and other unbreakable blocks (Bug)
Aeris flowers are supposed to clear out an area around itself when it's placed at or below y=15 in order to make room for mobs to spawn around it. Aeris flowers are also able to break bedrock and drop them in item form, allowing the player to obtain bedrock as soon as they find an aeris flower.

## 5. Claymation drops its loot pool every time a form dies (Bug)
[TragicMC 1.8 fixed this](https://github.com/TragicNeko/TragicMC2-1.8/blob/947c692193919465a63b97080633b9f858fb39e5/src/main/java/tragicneko/tragicmc/entity/boss/EntityClaymation.java#L52), it did this by adding a check to make sure its form is its original form (0). 
[The 1.7.10 version did not have this check](https://github.com/TragicNeko/TragicMC2/blob/b2be94311c192ab9561438497eb957fbe42dddd0/src/main/java/tragicneko/tragicmc/entity/boss/EntityClaymation.java#L4).

## 6. Unused music in gamefiles (Oversight?? not sure)
There's a few unused tracks in the game's music/dimension asset folder. All of the music originating from Metroid (should be all of them) are not used ingame in any meaningful way. As a result, this music takes up filesize without contributing anything.

TragicMC2's 1.8 version has a musicticker that plays this music, whereas the 1.7.10 version does not. Whether or not you want to go through the effort of readding this musicticker is up to you, but if you want to converse on filesize then you should probably just remove them. These files take up around ~32.8 megabytes AFAIK.

**Comment by quentin452** [comment]
Check list

- [x] Issue 1 moved to https://github.com/quentin452/TragicMC2-Continuation/issues/6
- [ ] Issue 2 moved to https://github.com/quentin452/TragicMC2-Continuation/issues/5
- [x] 3
- [x] 4
- [x] 5
- [x] 6

**Comment by quentin452** [comment]
the second bug , for now don't have clues

**Comment by quentin452** [comment]
can you give me which item is "Ender Amulet" i can't find it

**Comment by quentin452** [comment]
maybe by "Ender Amulet" you mean Ender Dragon Amulet

**Comment by quentin452** [comment]
Anyway if its Ender Dragon Amulet , for me its unreproducable

**Comment by totalgooberdeath** [comment]
Commented on the other issue, enderman amulet has the silk touch effect. Ender dragon amulet deletes the blocks you're in if you take suffocation damage.
