### ISSUE TITLE
Enderman Amulet crash (Major crash) (For me unreproducable)

### ISSUE THREAD

**Issue by quentin452** [quentin452/TragicMC2-Continuation#6]
Ender Amulet lets you mine blocks faster with your bare hands and silktouches them if you do it this way. If you mine any part of a double-tall plant block (e.g, grass, rose bush, large fern, etc.), the world will be corrupted and you will have to load from a backup.
HOW TO RECREATE

    Spawn in/obtain Ender Amulet
    Equip ender amulet (either right click with an empty amulet slot available or navigate to the amulet GUI and equip it manually)
    Punch any double-tall plant block
    Game will turn into a greyish-blue screen and boot you out of the world. The world will crash every time it tries to be reloaded

**Comment by totalgooberdeath** [comment]
It is the enderman amulet. Sorry for not responding earlier, I was at work.

**Comment by quentin452** [comment]
Do you have a crash report , for me its unreproducable even with the EnderMan Amulet

**Comment by totalgooberdeath** [comment]
At work right now, will test when I get off work in 2 hours
